import Image from "next/image";
import { ResourceLibrary } from "./components/ResourceLibrary";
import { SiteFooter } from "./components/SiteFooter";
import { SiteHeader } from "./components/SiteHeader";

const samplePartners = ["harbor", "Common Good", "little light", "gather"];

export default function Home() {
  return <><SiteHeader /><main><section className="relative overflow-hidden bg-[#173d37] text-white"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(#e5f36b_1px,transparent_1px)] [background-size:22px_22px]" /><div className="relative mx-auto grid max-w-6xl gap-12 px-5 py-16 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="inline-flex rounded-full bg-[#e5f36b] px-3 py-1 text-xs font-black uppercase tracking-wider text-[#173d37]">Free resource library</p><h1 className="mt-6 max-w-2xl text-5xl font-bold tracking-tight sm:text-6xl">Make room for hope.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-[#c9dad2]">Open Media Collective creates free videos, graphics, guides, and social resources that help faith communities tell a truer, kinder story.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#resources" className="rounded-full bg-[#e5f36b] px-5 py-3 text-sm font-bold text-[#173d37] transition hover:bg-white">Explore the library</a><a href="#about" className="rounded-full border border-[#7d9a91] px-5 py-3 text-sm font-bold text-white transition hover:border-white">Why we exist</a></div><div className="mt-10 flex items-center gap-4 text-sm text-[#c9dad2]"><div className="flex -space-x-2"><span className="h-8 w-8 rounded-full border-2 border-[#173d37] bg-[#edb8ad]" /><span className="h-8 w-8 rounded-full border-2 border-[#173d37] bg-[#f3dc7a]" /><span className="h-8 w-8 rounded-full border-2 border-[#173d37] bg-[#9bd4c3]" /></div><span>Built to be shared, adapted, and passed on.</span></div></div><div className="relative mx-auto w-full max-w-lg"><div className="absolute -right-5 -top-5 h-24 w-24 rounded-full bg-[#ef947f]" /><div className="absolute -bottom-5 -left-5 h-24 w-24 rounded-[2rem] bg-[#e5f36b]" /><div className="relative overflow-hidden rounded-[2rem] border-8 border-white/10 shadow-2xl"><Image src="/images/community-creative-team.png" alt="Community team planning creative materials together" width={1280} height={720} priority className="aspect-[4/3] w-full object-cover" /><div className="absolute bottom-4 left-4 rounded-2xl bg-white px-4 py-3 text-sm font-bold text-[#173d37] shadow-lg"><span className="mr-2 text-[#e57b63]">*</span> Stories worth sharing</div></div></div></div></section>
<section className="border-b border-[#dce5d7] bg-white"><div className="mx-auto max-w-6xl px-5 py-8"><p className="text-center text-xs font-bold uppercase tracking-[.16em] text-[#82958e]">Made to serve local communities</p><div className="mt-5 grid grid-cols-2 gap-3 text-center sm:grid-cols-4">{samplePartners.map((name, index) => <div key={name} className={"rounded-xl py-3 text-sm font-black " + (index % 2 ? "bg-[#f5e7a5] text-[#755f09]" : "bg-[#e7f0e8] text-[#28584e]")}>{name}</div>)}</div></div></section>
<ResourceLibrary />
<section id="about" className="overflow-hidden bg-[#f0eee6]"><div className="mx-auto max-w-6xl px-5 py-16 sm:py-24"><div className="grid gap-12 lg:grid-cols-[.95fr_1.05fr]"><div><p className="eyebrow">About Open Media Collective</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-[#173d37] sm:text-4xl">Better stories can help people find their way.</h2><p className="mt-5 text-lg leading-8 text-[#52706a]">We are a small collective of makers, communicators, and community builders. We believe thoughtful media should not be reserved for the teams with the biggest budgets.</p><p className="mt-4 leading-7 text-[#52706a]">Everything here is made to be useful at the point of need: easy to adapt, generous in tone, and grounded in the real places people live and serve.</p></div><div className="grid gap-5 sm:grid-cols-2"><article className="rounded-[1.5rem] bg-[#173d37] p-7 text-white"><p className="text-3xl text-[#e5f36b]">*</p><h3 className="mt-5 text-xl font-bold">Our vision</h3><p className="mt-3 leading-7 text-[#c9dad2]">Faith communities equipped to tell stories of grace, welcome, and hope in every neighborhood.</p></article><article className="rounded-[1.5rem] bg-[#e5f36b] p-7 text-[#173d37]"><p className="text-3xl">*</p><h3 className="mt-5 text-xl font-bold">Our mission</h3><p className="mt-3 leading-7 text-[#345b52]">Create and share practical media tools that help people communicate with clarity, care, and courage.</p></article></div></div><div className="mt-12 grid gap-4 border-t border-[#d3d9ce] pt-8 sm:grid-cols-3"><div><p className="font-bold text-[#173d37]">Open-handed</p><p className="mt-1 text-sm leading-6 text-[#52706a]">Useful resources should travel freely.</p></div><div><p className="font-bold text-[#173d37]">Human-first</p><p className="mt-1 text-sm leading-6 text-[#52706a]">We choose dignity over noise every time.</p></div><div><p className="font-bold text-[#173d37]">Local-hearted</p><p className="mt-1 text-sm leading-6 text-[#52706a]">The best communication sounds like home.</p></div></div></div></section></main><SiteFooter /></>;
}
